services:
  db: 
    image: postgres:16-alpine
    container_name: inspecao-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: inspecao-db
    ports:
      - "5432:5432"
    volumes:
      - ./db-data:/var/lib/postgresql/data

volumes: 
  db-data: